### PR TITLE
Add Cox PH to fitModel

### PR DESCRIPTION
**Pull request by daniel-barnett**

### CODE REVIEW

**Comment by tmelliott** [comment]
macOS devel seems broken (unrelated to the package) - is this otherwise complete @daniel-barnett ?

**Comment by daniel-barnett** [comment]
Yep, should be good to go

**Comment by daniel-barnett** [comment]
Actually, I want to refactor this slightly to make the interface easier

**Comment by tmelliott** [comment]
#148 closed, so rebasing to dev.

**Comment by tmelliott** [comment]
Hi @daniel-barnett - merging this in as I presume you wont be working on it any more :wink:

**Pull request merged**
