### PR TITLE
Feature/code writing

### PR DESCRIPTION
**Pull request by tmelliott**
Adds code tidying feature, allowing pretty-printing of tidyverse-style scripts.

### CODE REVIEW

**Comment by tmelliott** [comment]
Overall structure is good. A few things to do:

- [ ] the combined pipes are wrong, `data %<>%` is the equivalent to `data <- data %>%`
The following ...
```r
data <- read_data() %>% filter()
data %<>% mutate()
```
Should be converted to
```r
data <- read_data %>% 
    filter() %>%  # in your function, this is a %<>% instead
    mutate()
```

- [ ] to improve code readability, could you go through and tidy/improve consistency, e.g.,
  - using `<-` instead of `=` for assignment
  - [spaces around operators](https://style.tidyverse.org/syntax.html#spacing)
  - try keep all lines [under 80 characters](https://style.tidyverse.org/syntax.html#long-lines)
  - [no need for `return()`](https://style.tidyverse.org/functions.html#return) (last line of `tidy_code`)

- [ ] write tests - these should be in two forms
  - short tests (such as for the example above), where we check the code string is as we expect
  - longer tests, where we check that the result of parsing the code is the same as what we got initially

**Comment by tmelliott** [comment]
One more thing that's needed is to __export__ the main tidy function (and add documentation to it).

Here's an example of some [roxygen2](http://r-pkgs.had.co.nz/man.html) comments for documentation (Line 12 is most important, it means the function is available when you load the library!)
https://github.com/iNZightVIT/iNZightTools/blob/4093703edf35e6117833f7f067f3f12f7dbe55e0/R/import_data.R#L1-L13

**Comment by tmelliott** [comment]
That's looking much better. On line 43 you have `printcode6` which I assume should be `print_code`. 

Piping still isn't quite right. Here's what I get after fixing the above, and on the `before.txt` file you sent a while back:
```r
gapminder_2008_ex %<>%                                                                              
  tibble::add_column(
    Region.reord =
      factor(
        gapminder_2008_ex$Region,
        levels =
          c(                                                                                        
            "East Asia & Pacific",
            "Europe & Central Asia",
            "Middle East & North Africa",
            "America",
            "Sub-Saharan Africa",
            "South Asia"
          )
      ),
      .after = "Region"
  )
 
 gapminder_2008_ex.sorted <-
  gapminder_2008_ex %>%
    dplyr::arrange( Year, desc( Country ), Imports)
 
 gapminder_2008_ex.sorted %<>%
    tibble::add_column(
      log.e.CO2Emissions =
        log( gapminder_20),
        .after = "CO2Emissions"
    )
```

* The first line should use a `<-` operator. 

* The remainder of what's written is technically correct, but we would prefer something like
```r
 gapminder_2008_ex.sorted <-
  gapminder_2008_ex %>%
    dplyr::arrange( Year, desc( Country ), Imports) %>%
    tibble::add_column(
      log.e.CO2Emissions =
        log( gapminder_20),
        .after = "CO2Emissions"
    )
```

**Comment by lucy0619** [comment]
gapminder_2008_ex %<>%                                                                              
  tibble::add_column(
    Region.reord =
      factor(
        gapminder_2008_ex$Region,
        levels =
          c(                                                                                        
            "East Asia & Pacific",
            "Europe & Central Asia",
            "Middle East & North Africa",
            "America",
            "Sub-Saharan Africa",
            "South Asia"
          )
      ),
      .after = "Region"
  )

do you mean this %<>% should be <- ?

**Comment by tmelliott** [comment]
All seems to be looking really good. A few more small things:

- [ ] Generate documentation. This is done using `devtools::document()` which will make some changes and create a new file in the `man` directory, which you can commit and push

- [ ] Add your name to the `DESCRIPTION` file

- [ ] Add an entry to the `NEWS.md` file in the first section where it says "Release date: TBA" (something along the lines of "added code tidying functionality")

**Pull request merged**
